name: Data Preprocessing dan Analisis Eksperimen MSML

description: |
  Workflow ini digunakan untuk melakukan preprocessing dataset housing,
  membersihkan data dari missing values, dan melakukan analisis eksploratori serta eksperimen.

on:
  push:
    branches: ["main"]
  workflow_dispatch:  # Memungkinkan untuk menjalankan workflow secara manual

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Menggunakan versi stabil

      - name: Set up Python
        uses: actions/setup-python@v2  # Menggunakan versi stabil
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt  # Perbarui path ke requirements.txt di MLProject

      - name: Preprocessing Data
        env:
          input_file: /mnt/data/HousingData.csv
          output_file: /mnt/data/HousingData_clean.csv
        run: |
          python automate_Nama-siswa.py

      - name: Echo success message
        run: echo "Preprocessing selesai, hasil disimpan di HousingData_clean.csv"

  # Other jobs (analysis, visualization, etc.) remain unchanged
