name: Data Preprocessing dan Analisis Eksperimen MSML

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Workflow-CI/MLProject/requirements.txt

      - name: Preprocessing Data
        env:
          input_file: Workflow-CI/MLProject/preprocessing/HousingData.csv
          output_file: Workflow-CI/MLProject/preprocessing/HousingData_clean.csv
        run: |
          python Workflow-CI/MLProject/preprocessing/automate_Fathan-Rezah-Ardhiansa.py

      - name: Echo success message
        run: echo "Preprocessing selesai, hasil disimpan di HousingData_clean.csv"