name: CI Workflow for MLflow Project

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'MLProject/**'
      - 'conda.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-activate-base: false

      - name: Install dependencies
        run: |
          conda env create -f MLProject/conda.yaml
          conda activate mlflow-env
          pip install mlflow

      - name: Run model training
        run: |
          conda activate mlflow-env
          python MLProject/modelling.py

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name .
          docker push your-dockerhub-username/your-image-name
          
      - name: Upload model artifacts
        uses: actions/upload-artifact@v2
        with:
          name: model-artifacts
          path: ./model
