name: Basic ML Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout (Biar namanya "Run actions/checkout@v3")
    - uses: actions/checkout@v3

    # 2. Setup Python (Saya set 3.12 biar persis gambar kamu)
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Check Env (Langkah custom sesuai gambar)
    - name: Check Env
      run: |
        pwd
        ls -R

    # 4. Install dependencies (Langkah custom sesuai gambar)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn numpy matplotlib

    # 5. Run mlflow project (Langkah custom sesuai gambar)
    - name: Run mlflow project
      run: |
        cd SMSML_Fathan-Rezah-Ardhiansa/Membangun_model
        # --experiment-name ini PENTING biar langkah selanjutnya bisa nemu ID-nya
        mlflow run . --env-manager=local --experiment-name "Housing_Price_Prediction"

    # 6. Get latest MLflow run_id (Langkah custom sesuai gambar)
    - name: Get latest MLflow run_id
      run: |
        cd SMSML_Fathan-Rezah-Ardhiansa/Membangun_model
        python -c "import mlflow; runs = mlflow.search_runs(experiment_names=['Housing_Price_Prediction']); print(f'Latest Run ID: {runs.iloc[0].run_id}') if not runs.empty else print('No runs found')"